INITIAL_VALUE_INPUT = "initial-value-input"
MONTHLY_CONTRIBUTION_INPUT = "monthly-contribution-input"
YEARS_SLIDER = "years-slider"
SIMULATION_COUNT_SLIDER = "simulation-count-slider"
SEED_DROPDOWN = "seed-dropdown"

ASSET_TABLE = "asset-table"
ADD_ASSET_BUTTON = "add-asset-button"
WEIGHT_SUM_TEXT = "weight-sum-text"
MARKET_PRESET_DROPDOWN = "market-preset-dropdown"
MARKET_PRESET_SUMMARY = "market-preset-summary"
PREDEFINED_ASSET_DROPDOWN = "predefined-asset-dropdown"

PAIRWISE_CORRELATION_SLIDER = "pairwise-correlation-slider"
CORRELATION_TABLE = "correlation-table"

RUN_BUTTON = "run-button"
ERROR_MESSAGE = "error-message"
RESULTS = "results"
FINAL_VALUES_STORE = "final-values-store"
DOWNLOAD_BUTTON = "download-button"
DOWNLOAD = "download"

STRESS_SCENARIO_TABLE = "stress-scenario-table"
ADD_STRESS_SCENARIO_BUTTON = "add-stress-scenario-button"
STRESS_SCENARIO_CHART = "stress-scenario-chart"
STRESS_SCENARIO_MESSAGE = "stress-scenario-message"

URL = "url"
NAV_PORTFOLIO_LINK = "nav-portfolio-link"
NAV_GBS_LINK = "nav-gbs-link"
NAV_ADVANTAGE_LINK = "nav-advantage-link"
PORTFOLIO_PAGE = "portfolio-page"
GBS_PAGE = "gbs-page"
CAVEATS_PAGE = "caveats-page"
THEORY_PAGE = "theory-page"
ADVANTAGE_PAGE = "advantage-page"
GUIDE_PAGE = "guide-page"

GBS_ASSET_TABLE = "gbs-asset-table"
GBS_ADD_ASSET_BUTTON = "gbs-add-asset-button"
GBS_WEIGHT_SUM_TEXT = "gbs-weight-sum-text"
GBS_MARKET_PRESET_DROPDOWN = "gbs-market-preset-dropdown"
GBS_MARKET_PRESET_SUMMARY = "gbs-market-preset-summary"
GBS_PREDEFINED_ASSET_DROPDOWN = "gbs-predefined-asset-dropdown"
GBS_PAIRWISE_CORRELATION_SLIDER = "gbs-pairwise-correlation-slider"
GBS_CORRELATION_TABLE = "gbs-correlation-table"

GBS_DEGREE_RADIO = "gbs-degree-radio"
GBS_STRENGTH_SLIDER = "gbs-strength-slider"
GBS_MAX_SHOTS_DROPDOWN = "gbs-max-shots-dropdown"
GBS_SEED_DROPDOWN = "gbs-seed-dropdown"
GBS_RUN_BUTTON = "gbs-run-button"
GBS_ERROR_MESSAGE = "gbs-error-message"
GBS_RESULTS = "gbs-results"

ADVANTAGE_PROBLEM_DROPDOWN = "advantage-problem-dropdown"
ADVANTAGE_PROBLEM_DESCRIPTION = "advantage-problem-description"
ADVANTAGE_VARIABLE_COUNT_DROPDOWN = "advantage-variable-count-dropdown"
ADVANTAGE_MATRIX_TABLE = "advantage-matrix-table"
ADVANTAGE_TUNING_RADIO = "advantage-tuning-radio"
ADVANTAGE_MAX_SHOTS_DROPDOWN = "advantage-max-shots-dropdown"
ADVANTAGE_SEED_DROPDOWN = "advantage-seed-dropdown"
ADVANTAGE_RUN_BUTTON = "advantage-run-button"
ADVANTAGE_ERROR_MESSAGE = "advantage-error-message"
ADVANTAGE_RESULTS = "advantage-results"
QISKIT_DOWNLOAD_BUTTON = "qiskit-download-button"
QISKIT_DOWNLOAD_MESSAGE = "qiskit-download-message"
QISKIT_DOWNLOAD = "qiskit-download"
