INITIAL_VALUE_INPUT = "initial-value-input"
MONTHLY_CONTRIBUTION_INPUT = "monthly-contribution-input"
YEARS_SLIDER = "years-slider"
SIMULATION_COUNT_SLIDER = "simulation-count-slider"
SEED_DROPDOWN = "seed-dropdown"

ASSET_TABLE = "asset-table"
ADD_ASSET_BUTTON = "add-asset-button"
WEIGHT_SUM_TEXT = "weight-sum-text"

PAIRWISE_CORRELATION_SLIDER = "pairwise-correlation-slider"
CORRELATION_TABLE = "correlation-table"

RUN_BUTTON = "run-button"
ERROR_MESSAGE = "error-message"
RESULTS = "results"
FINAL_VALUES_STORE = "final-values-store"
DOWNLOAD_BUTTON = "download-button"
DOWNLOAD = "download"

URL = "url"
NAV_PORTFOLIO_LINK = "nav-portfolio-link"
NAV_GBS_LINK = "nav-gbs-link"
PORTFOLIO_PAGE = "portfolio-page"
GBS_PAGE = "gbs-page"

GBS_DEGREE_RADIO = "gbs-degree-radio"
GBS_STRENGTH_SLIDER = "gbs-strength-slider"
GBS_MAX_SHOTS_DROPDOWN = "gbs-max-shots-dropdown"
GBS_SEED_DROPDOWN = "gbs-seed-dropdown"
GBS_RUN_BUTTON = "gbs-run-button"
GBS_ERROR_MESSAGE = "gbs-error-message"
GBS_RESULTS = "gbs-results"
